### ISSUE TITLE
Feature: User can code on HTML, CSS, and JavaScript sections and receive result

### ISSUE THREAD

**Issue by Han-Zhang-Code** [Han-Zhang-Code/Code-Journal-React#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can code on HTML, CSS, and JavaScript sections and receive result

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once User finished coding on HTML, CSS or JavaScript Section, they will 
   received corresponding result at Result Section based on their code
User can save their code by hitting the save button at top right corner

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

mobile version: 
![Screen Shot 2022-07-25 at 3 55 39 PM](https://user-images.githubusercontent.com/103379415/180888059-0461b6d6-41d4-4ef2-a37d-aafb0e9cd6ab.png)

window version:
![Screen Shot 2022-07-25 at 3 56 00 PM](https://user-images.githubusercontent.com/103379415/180888073-cc22382d-199c-49ba-8254-7ec9a8ab8452.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to insert pre-written css, html, and JavaScript code into the table
- [x] Update `schema.sql` create table that store html, css, and JavaScript code

### ☁️ Server Tasks

- [x] Update `server/index.js` to use post method to store user's code into the database table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Install codemirror and react-codemirror2 package
- [x] Rename the hello-world.jsx to code-editor.jsx and clean up the file,  create a new component named CodeEditor, which will return to two divs, one for HTML, CSS and JavaScript editing area, one for result window, initial state for the HTML, CSS, and JavaScript to empty string, as well as set each state as a hook.
- [x] Inside the first div created in last step, call ‘Editor’ Component three times for each language and pass the corresponding initial state value as value attribute, and corresponding ‘setState’ as onChange attribute,  create Editor component in a new jsx file in the components folder.  
- [x] In the Editor component file, import necessary library from codemirror and react-codemirror2 package:  xml, javascript, and css mode from codemirror, and most importantly the Controlled component from react-codemirror2, Destructure the value and onChange from props. 
- [x] In the render function of Editor component, call the Controlled component with onBeforeChange set to ‘onChange’ from the props, set value equal to value from the props.
- [x] In the CodeEditor component, create a template literals that basically contains a html file, inside the body tag of the html tag, put the html variable that created earlier in the state variables, put the css variable inside the script tag and put the javascript variable to the script tag.  Store the template literals to a variable and call this variable in the result section. 
- [x] Store the html, css, and javascript code into the database.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
