### ISSUE TITLE
Feature: User can view a specific entry code

### ISSUE THREAD

**Issue by Han-Zhang-Code** [Han-Zhang-Code/Code-Journal-React#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can view a specific entry code when they click on the entry title on the view entries page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when user click on the entry title on the view entries page, the app will direct to the specific code editor page that user selected  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![180889329-a12568ec-1cd7-40a9-83fc-599665b436fc](https://user-images.githubusercontent.com/103379415/181654861-9d1085a3-0a98-4dab-8a2e-f000e2ebb8b7.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] no need to change schema.sql and data.sql at this time

### ☁️ Server Tasks

- [ ] Update `server/index.js` to create a get method to pull a specific code entry based on the entryId
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] when user click on the entry title on the view entries page, the app will direct to the corresponding code editor page that user selected
- [ ] when user click the "Entries" button on the nav bar, the app will direct to view Entries page

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
