### ISSUE TITLE
Feature: User can save their code with title, picture, and description

### ISSUE THREAD

**Issue by Han-Zhang-Code** [Han-Zhang-Code/Code-Journal-React#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save their code with title, picture, and description

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when user click the save button on the top, a saving module will popup

all fields will be require in order to save (title, photo url and description)

when user click the cancel button, the app will return to code editor

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

mobile version:
![Screen Shot 2022-07-25 at 4 02 22 PM](https://user-images.githubusercontent.com/103379415/180888921-867e851e-249d-4c45-b624-7e1a9adab2fb.png)

windows version:
![Screen Shot 2022-07-25 at 4 02 39 PM](https://user-images.githubusercontent.com/103379415/180888929-ff654771-c5ec-4928-8a11-a1947044f492.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] review the data.sql and schema.sql, no change needed at this time

### ☁️ Server Tasks

- [x] Update `server/index.js` to insert title, picture and description of the code entry into the database along with html, css, and JavaScript code
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update CodeEditor component to create a module and hide it, once user click on the save button on the top, this module will pop up for user to input necessary information about the code, all filed will be required
- [x] when user click on cancel button of the module, the app will go back to code editor
- [x] when user click on the save button of the module, the app will save user input to database

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
