### ISSUE TITLE
Feature: User can view their code entries 

### ISSUE THREAD

**Issue by Han-Zhang-Code** [Han-Zhang-Code/Code-Journal-React#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their code entries 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

if there is no entries have been recored, a no entries message will appear, this page will also be the landing page for the app

user can click the “new” button which will direct to code editor page to create a new entry

user can click the entry title to direct to corresponding code editor page which saved in database

user can click on the “Entries” button on the top to direct to view entries page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

mobile version:
![Screen Shot 2022-07-25 at 4 05 26 PM](https://user-images.githubusercontent.com/103379415/180889300-93a415f7-0748-4cda-90ec-df46db66f1c8.png)
windows version:
![Screen Shot 2022-07-25 at 4 06 04 PM](https://user-images.githubusercontent.com/103379415/180889329-a12568ec-1cd7-40a9-83fc-599665b436fc.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Review data.sql and schema.sql, no need to change at this time

### ☁️ Server Tasks

- [ ] Update `server/index.js` to create GET method to pull all the data from the database 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a page for user to view the entries they have entered so far
- [ ] after user saves an entry, the app will direct to view entries page that just created
- [ ] when user click the "NEW" button on the top, the app will direct to empty codeEditor page to create a new entry
- [ ] when user click the "Entries" button on the nav bar anytime, the app will direct to view Entries page
- [ ] when no entries has recored, display a no entries message
- [ ] set view entries page to landing page for the app

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
