### ISSUE TITLE
Feature: User can edit their code entries

### ISSUE THREAD

**Issue by Han-Zhang-Code** [Han-Zhang-Code/Code-Journal-React#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit their code entries

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when user click on the pencil icon, the Edit Entry module will pop up to edit the entry saving information

after editing, when user click the save button, the app will return to view entries page with edited saving information

while editing, if user click “Entries” button on the top, the app will discard the change and return to view entries page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

mobile version:
![Screen Shot 2022-07-25 at 4 28 06 PM](https://user-images.githubusercontent.com/103379415/180891608-63c58b85-3418-4340-99c0-112e3db250ae.png)

windows version:
![Screen Shot 2022-07-25 at 4 28 47 PM](https://user-images.githubusercontent.com/103379415/180891615-aa563cc3-1b57-4e9f-8f6d-6694aaed6002.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] no need to change data.sql and schema.sql at this time

### ☁️ Server Tasks

- [ ] Update `server/index.js` to create patch method to update specific entry in database based on EntryId 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] add appropriate data-view props to each CodeEditor component and display 'SAVE' button accordingly: hide the button when its on viewEntries data-view so user cant save; display the button when its on createEntry data-view
- [ ] Update ViewEntries component to create an edit icon next to each entry
- [ ] Create a EditEntry component to Edit entry when user click on the edit icon
- [ ] use fetch method to fetch patch method in the CodeEditor component, and call this method according to data-view prop
- [ ] make sure saving the entry does not create a new entry 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
