### ISSUE TITLE
Feature: User can delete their code entries 

### ISSUE THREAD

**Issue by Han-Zhang-Code** [Han-Zhang-Code/Code-Journal-React#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete their code entries 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when user click the pencil icon, the Edit Entry module will pop up with an option to delete the entry that user clicked on

when user click the Delete Entry button, the confirmation module will pop up , if user click on cancel button, the app will go back to Edit Entry module; if user click on the confirm button, the selected entry will be deleted along with corresponding code in code editor

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

mobile version:
![Screen Shot 2022-07-25 at 4 31 53 PM](https://user-images.githubusercontent.com/103379415/180891860-8d09b615-eb72-4d18-b26b-f26a8035f631.png)

windows version:
![Screen Shot 2022-07-25 at 4 32 23 PM](https://user-images.githubusercontent.com/103379415/180891871-970bff98-f2b3-4c01-b6fa-4d3a5f172c39.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] no need to change data.sql and schema.sql at this time

### ☁️ Server Tasks

- [ ] Update `server/index.js` to create a DELETE route to delete an entry based on entryId
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Update CodeEditor component to create a delete button on saving modal
- [ ] make sure the saving modal display cancel button on create entry page and display delete button on editing page
- [ ] when user confirm on delete, the app will delete the entry that user selected
- [ ] when user hit the cancel button on confirmation modal, the app will go back to saving modal

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
